### PR TITLE
Add Expanse dices

### PR DESCRIPTION
**Pull request by Swiip**
Hey, I recently stumble upon your bot and I think it's nice, it's the only one that is able to actually show some dice illustrations.

I plan to play to The Expanse RPG and I really like their custom dices. Also, I found the assets freely on Github (https://github.com/Foxfyre/expanse/tree/main/ui/dice). So Imagined suggesting them to add to the bot.

I'm a developer so I found my way. But it's too long since I didn't practice Java, so I did some obvious changes but wasn't able to test it.

Hope you like it!

### CODE REVIEW

**Comment by twonirwana** [comment]
Wow that is great. Give me a few days for tests and documentation. Do you have a command config for the Expanse RPG that I can add to the quickstart/examples?

**Comment by Swiip** [comment]
I prepared buttons with the existing illustrations that looks like that

```
/custom_dice start
buttons:
    2d6 col 'red_and_gold' + 1d6 @ MCRN;
    2d6 col 'blue_and_gold' + 1d6 @ UN;
    2d6 col 'black_and_gold' + 1d6 @ OPA;
answer_format: only_dice
dice_image_style: polyhedral_alies_v2
dice_image_color: purple_and_silver
```

I imagine that given the new dices, it could become like this

```
/custom_dice start
buttons:
    2d6 col 'mars_dark' + 1d6 col 'mars_light' @ MCRN;
    2d6 col 'earth_dark' + 1d6 col 'earth_light' @ UN;
    2d6 col 'belt_dark' + 1d6 col 'belt_light' @ OPA;
answer_format: only_dice
dice_image_style: expanse
```

The system is basically 3d6 with a special color for the third one being the "Drama Die"

**Comment by twonirwana** [comment]
> ```
> /custom_dice start
> buttons:
>     2d6 col 'mars_dark' + 1d6 col 'mars_light' @ MCRN;
>     2d6 col 'earth_dark' + 1d6 col 'earth_light' @ UN;
>     2d6 col 'belt_dark' + 1d6 col 'belt_light' @ OPA;
> answer_format: only_dice
> dice_image_style: expanse
> ```

You don't use the protogen dice, is this an oversight?

**Comment by Swiip** [comment]
Not an oversight, protogen is not a playable faction in the book, more kind of antagonists. Maybe for the GM, I don't know yet. But as it was there in the folder, I added it.

Thanks a huge lot for wrapping this up! I know how much testing and documentation is important!

**Pull request merged**
