### PR TITLE
Switch the random number generator to Sfc64

### PR DESCRIPTION
**Pull request by tertu-m**
This switches the random number generator to an implementation of Sfc64, a recent generator with good performance and statistical quality, and seeds it using random data requested from a high quality source.

### CODE REVIEW

**Comment by twonirwana** [comment]
Thanks for the contribution but i am a little hesitant because i can not really verify your implementation is better than the default (i have simply no knowledge in this area). If there is a better random number generator than the default one, then i would prefer to import it with a well maintained library. For example: org.apache.commons.math3.random.RandomDataGenerator using Well19937c would be a option

**Comment by tertu-m** [comment]
The NumPy documentation [](https://numpy.org/doc/stable/reference/random/bit_generators/sfc64.html) for this RNG provides a little more information about it. It's pretty well characterized (and this is a direct translation of the C implementation), but I would also be OK changing this to use another one (honestly, Java 18 and later have some pretty decent choices in the standard library).

**Comment by twonirwana** [comment]
Thanks again for the input, give me some days so i can read a litte to the topic.

**Comment by twonirwana** [comment]
Ok, looks good but could you add a comment with a link to the C implementation you used as reference.

**Comment by tertu-m** [comment]
Done. I also squashed it.

**Pull request merged**
